version: '3.8'

services:
  mikasuzu-portal:
    container_name: mikasuzu-portal
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/usr/src
    tty: true
    ports:
      - 4321:4321